exports.userController = require('./userController')
exports.postController = require('./postController')
exports.profileController = require('./profileController')
exports.likeController = require('./likeController')
exports.commentController = require('./commentController')